import yekanBakh from "@/core/assets/style/font/yekanBakh";
import type { Metadata } from "next";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "sonner";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" suppressHydrationWarning>
      <body
        className={`${yekanBakh.variable} antialiased`}
        suppressHydrationWarning
      >
        <NextTopLoader />
        <Toaster />

        {children}
      </body>
    </html>
  );
}
